### PR TITLE
adding  group

### PR DESCRIPTION
**Pull request by bek2-ful**
new group for ssh

### CODE REVIEW

**Review by mbg — CHANGES_REQUESTED** [review]
Your commit includes a bunch of files that shouldn't be there. Please remove them / only update `groups.yaml`

**Comment by mbg** [comment]
Just push a commit to your branch which deletes the files - I see you've already done that (with multiple commits). You could have removed all the files in one commit, but this is fine.

**Comment by bek2-ful** [comment]
hi, i'm sorry but i did not see my group in the list. should i do anything about it?

**Review by mbg — CHANGES_REQUESTED** [review]
You now seem to have added the group to the configuration file twice. It only needs to be there once.

**Comment by bek2-ful** [comment]
Hi, I'm quite concerned as my group is not in the group list in Canvas nor in the yaml file. Is there anything that I should do?

**Comment by mbg** [comment]
@bek2-ful Yes: you haven't addressed my review comment yet. Once you have done that, and there are no other problems, we can merge this.

**Review by bek2-ful — COMMENTED** [review]
reviewed

**Comment by bek2-ful** [comment]
Hi, I’m confused on what address that you meant. Does this mean my team will be randomised?☹️ I’m so sorry for the inconvenience

**Review by mbg — APPROVED** [review]

**Comment by mbg** [comment]
@bek2-ful You made the change I requested in https://github.com/uob-sepp/groups-2024/pull/116/commits/8bd47984126e9d3ac71210302aa39e574d0b77f2, but I just hadn't seen it until now. As you can see, it has passed the CI, and I have now merged your PR.

Nobody involved in a pending PR to register their group was randomly allocated to a group, provided the PR was open before the deadline on Wednesday.

**Pull request merged**
